# Generated by Django 5.1.3 on 2024-12-03 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('admin', 'Администратор'), ('teacher', 'Преподаватель'), ('student', 'Студент')], null=True, verbose_name='Роль'),
        ),
    ]
