# Generated by Django 5.1.3 on 2024-12-02 10:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Зачисление на курс',
                'verbose_name_plural': 'Зачисления на курс',
                'ordering': ['pk'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='course',
            name='unique_course_owner',
        ),
        migrations.RemoveConstraint(
            model_name='lesson',
            name='unique_lesson_owner',
        ),
        migrations.RemoveConstraint(
            model_name='module',
            name='unique_module_owner',
        ),
        migrations.AddField(
            model_name='enrollment',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials.course', verbose_name='Курс'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Студент'),
        ),
    ]
