# Generated by Django 4.2.2 on 2024-11-27 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0002_test_course'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'verbose_name': 'Ответ', 'verbose_name_plural': 'Ответы'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['test'], 'verbose_name': 'Вопрос', 'verbose_name_plural': 'Вопросы'},
        ),
        migrations.AlterModelOptions(
            name='test',
            options={'ordering': ['completed_at'], 'verbose_name': 'Тест', 'verbose_name_plural': 'Тесты'},
        ),
        migrations.AlterModelOptions(
            name='testresult',
            options={'verbose_name': 'Результат тестирования', 'verbose_name_plural': 'Результаты тестирования'},
        ),
        migrations.AlterField(
            model_name='testresult',
            name='score',
            field=models.CharField(choices=[('a', 'отлично'), ('b', 'хорошо'), ('c', 'удовлетворительно'), ('d', 'неудовлетворительно')], verbose_name='Оценка'),
        ),
    ]
