# Generated by Django 5.1.3 on 2024-12-04 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0004_test_lesson_test_module_alter_test_course_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='test',
            options={'ordering': ['pk'], 'verbose_name': 'Тест', 'verbose_name_plural': 'Тесты'},
        ),
        migrations.RemoveField(
            model_name='test',
            name='completed_at',
        ),
    ]
